# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-07 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='hood_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='location',
            field=models.CharField(choices=[('Nyarugenge', 'Kimisagara'), ('Kicukiro', 'Kagarama'), ('Gasabo', 'Kimihurura'), ('kayonza', 'Gahini'), ('Rwamagana', 'Nyakariro')], max_length=50, null=True),
        ),
    ]
