# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0002_auto_20191103_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='occupants',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
